- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

  
- name: creation groupe "tomee"
  group: name=tomee

- name: creation utilisateur "tomee"
  user: name=tomee group=tomee home=/home/tomee createhome=yes
  become: True
  become_method: sudo

- name: creation dossier
  file: path=/opt/tomee state=directory
    
- name: changer owner 
  file: path=/opt/tomee owner=tomee group=tomee state=directory recurse=yes
    
    
    
- name: download tomee
  get_url :  
    url : http://repo.maven.apache.org/maven2/org/apache/tomee/apache-tomee/7.0.3/apache-tomee-7.0.3-plus.tar.gz
    dest: /opt/tomee
    

- name: extraction de l'archive
  command: /bin/tar xvf /opt/tomee/apache-tomee-7.0.3-plus.tar.gz -C /opt/tomee --strip-components=1
  

- name: Changement propriétaire de webapps/work/temps
    shell: chown -R tomee /opt/tomee/webapps/
    shell: chown -R tomee /opt/tomee/work/
    shell: chown -R tomee /opt/tomee/temp/
    shell: chown -R tomee /opt/tomee/logs/
    
 - name: Creation du fichier tomee.service
  file: 
    path: /etc/systemd/system/tomee.service 
    state: touch

- name: écriture du contenu de tomee.service
  shell: echo "[Unit] \nDescription=Apache TomEE Web Application Container\nAfter=network.target \n\n[Service]\nType=forking\n\nEnvironment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64\nEnvironment=CATALINA_PID=/opt/tomee/temp/tomee.pid\nEnvironment=CATALINA_HOME=/opt/tomee\nEnvironment=CATALINA_BASE=/opt/tomee\nEnvironment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'\nEnvironment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'\n\nExecStart=/opt/tomee/bin/startup.sh\nExecStop=/opt/tomee/bin/shutdown.sh\n\nUser=tomee\nGroup=tomee\nUMask=0007\nRestartSec=10\nRestart=always\n\n[Install]\nWantedBy=multi-user.target " > /etc/systemd/system/tomee.service



- name: activer le service
  command: "{{ item }}"
  with_items:
    - "sudo systemctl daemon-reload"
    - "sudo systemctl start tomee"
    - "sudo systemctl status tomee"
